### ISSUE TITLE
Possibly incorrect gamma_entropy?

### ISSUE THREAD

**Issue by tomblaze** [blei-lab/ars-reparameterization#1]
The gamma entropy in the sparse gamma def program seems to not match Wikipedia (https://en.wikipedia.org/wiki/Gamma_distribution#Information_entropy) and also apparently doesn't match the gamma entropy as defined in the gamma branch of the repo.

Compare [6]: https://github.com/blei-lab/ars-reparameterization/blob/master/gamma/demo.ipynb

and

https://github.com/blei-lab/ars-reparameterization/blob/b20a84c28537d85e0aaf62cbbaacb6de9370f0a3/sparse%20gamma%20def/gamma_def.py#L12

I think the correct line is:

`return alpha-np.log(m)+sp.gammaln(alpha)+(1.-alpha)*sp.digamma(alpha)`

and the gradient should change to...

`gradient[:,0] = 1. + (1.-alpha)*sp.polygamma(1,alpha)`
`gradient[:,1] = -1./m`

It's possible I'm not understanding something but thought it was worth double-checking. Changing doesn't seem to much affect optimization/final ELBO.

**Comment by naesseth** [comment]
Hi, thanks for reaching out! Note that it is parameterized by the mean (m=alpha/beta) and shape (alpha) in the sparse gamma def. The parameterization used on Wikipedia is rate (beta) and shape (alpha). I think those expressions, i.e. both the notebook and sparse gamma DEF, should be correct.

**Comment by tomblaze** [comment]
Ah okay that does make sense.
Sorry to bother.
